-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_membership_card`;
DROP TABLE IF EXISTS `civicrm_membership_card_template`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_membership_card_template
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_membership_card_template` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MembershipCardTemplate ID',
  `name` varchar(255) NOT NULL COMMENT 'Template name',
  `description` text NULL COMMENT 'Template description',
  `card_width` int unsigned NULL DEFAULT 350 COMMENT 'Card width in pixels',
  `card_height` int unsigned NULL DEFAULT 220 COMMENT 'Card height in pixels',
  `background_color` varchar(7) DEFAULT '#ffffff' COMMENT 'Background color',
  `background_image` varchar(255) COMMENT 'Background image',
  `elements` longtext NULL COMMENT 'JSON data for card elements',
  `is_active` tinyint NULL DEFAULT 1 COMMENT 'Is template active',
  `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When template was created',
  `modified_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When template was modified',
  PRIMARY KEY (`id`))
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_membership_card
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_membership_card` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MembershipCard ID',
  `membership_id` int unsigned COMMENT 'FK to civicrm_membership',
  `template_id` int unsigned COMMENT 'FK to civicrm_membership_card_template',
  `card_data` longtext NULL COMMENT 'Generated card data',
  `qr_code` varchar(255) NOT NULL COMMENT 'QR code data',
  `barcode` varchar(255) NOT NULL COMMENT 'Bar code data',
  `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When card was created',
  `modified_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When card was modified',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_membership_card_membership_id FOREIGN KEY (`membership_id`) REFERENCES `civicrm_membership`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_membership_card_template_id FOREIGN KEY (`template_id`) REFERENCES `civicrm_membership_card_template`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;
