<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.membershipcard/xml/schema/CRM/Membershipcard/MembershipCardTemplate.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:62ea740e43e9ed7976878542feea4b0c)
 */
use CRM_Membershipcard_ExtensionUtil as E;

/**
 * Database access object for the MembershipCardTemplate entity.
 */
class CRM_Membershipcard_DAO_MembershipCardTemplate extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_membership_card_template';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MembershipCardTemplate ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Template name
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Template description
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Card width in pixels
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $card_width;

  /**
   * Card height in pixels
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $card_height;

  /**
   * Background color
   *
   * @var string|null
   *   (SQL type: varchar(7))
   *   Note that values will be retrieved from the database as a string.
   */
  public $background_color;

  /**
   * Background image
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $background_image;

  /**
   * JSON data for card elements
   *
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $elements;

  /**
   * Is template active
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * When template was created
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * When template was modified
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $modified_date;

  /**
   * Front Background color
   *
   * @var string|null
   *   (SQL type: varchar(7))
   *   Note that values will be retrieved from the database as a string.
   */
  public $front_background_color;

  /**
   * Back Background color
   *
   * @var string|null
   *   (SQL type: varchar(7))
   *   Note that values will be retrieved from the database as a string.
   */
  public $back_background_color;

  /**
   * Front Background image
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $front_background_image;

  /**
   * Back Background image
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $back_background_image;

  /**
   * JSON data for card elements
   *
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $front_elements;

  /**
   * JSON data for card elements
   *
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $back_elements;

  /**
   * Whether template supports both sides
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_dual_sided;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_membership_card_template';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Membership Card Templates') : E::ts('Membership Card Template');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique MembershipCardTemplate ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_membership_card_template.id',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Template name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.name',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'description' => E::ts('Template description'),
          'required' => FALSE,
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.description',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'card_width' => [
          'name' => 'card_width',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Card Width'),
          'description' => E::ts('Card width in pixels'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_membership_card_template.card_width',
          'default' => '350',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'card_height' => [
          'name' => 'card_height',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Card Height'),
          'description' => E::ts('Card height in pixels'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_membership_card_template.card_height',
          'default' => '220',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'background_color' => [
          'name' => 'background_color',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Background color'),
          'description' => E::ts('Background color'),
          'maxlength' => 7,
          'size' => CRM_Utils_Type::EIGHT,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.background_color',
          'export' => TRUE,
          'default' => '#ffffff',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'background_image' => [
          'name' => 'background_image',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Background image'),
          'description' => E::ts('Background image'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.background_image',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'elements' => [
          'name' => 'elements',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Elements'),
          'description' => E::ts('JSON data for card elements'),
          'required' => FALSE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.elements',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Active'),
          'description' => E::ts('Is template active'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_membership_card_template.is_active',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When template was created'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.created_date',
          'headerPattern' => '/created(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Created Date"),
          ],
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Modified Date'),
          'description' => E::ts('When template was modified'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.modified_date',
          'headerPattern' => '/modified(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'front_background_color' => [
          'name' => 'front_background_color',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Front Background color'),
          'description' => E::ts('Front Background color'),
          'maxlength' => 7,
          'size' => CRM_Utils_Type::EIGHT,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.front_background_color',
          'export' => TRUE,
          'default' => '#ffffff',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'back_background_color' => [
          'name' => 'back_background_color',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Back Background color'),
          'description' => E::ts('Back Background color'),
          'maxlength' => 7,
          'size' => CRM_Utils_Type::EIGHT,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.back_background_color',
          'export' => TRUE,
          'default' => '#ffffff',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'front_background_image' => [
          'name' => 'front_background_image',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Front Background image'),
          'description' => E::ts('Front Background image'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.front_background_image',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'back_background_image' => [
          'name' => 'back_background_image',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Back Background image'),
          'description' => E::ts('Back Background image'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.back_background_image',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'front_elements' => [
          'name' => 'front_elements',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Front Elements'),
          'description' => E::ts('JSON data for card elements'),
          'required' => FALSE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.front_elements',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'back_elements' => [
          'name' => 'back_elements',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Back Elements'),
          'description' => E::ts('JSON data for card elements'),
          'required' => FALSE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_membership_card_template.back_elements',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'is_dual_sided' => [
          'name' => 'is_dual_sided',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Dual Sided'),
          'description' => E::ts('Whether template supports both sides'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_membership_card_template.is_dual_sided',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_membership_card_template',
          'entity' => 'MembershipCardTemplate',
          'bao' => 'CRM_Membershipcard_DAO_MembershipCardTemplate',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'membership_card_template', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'membership_card_template', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
